// homework #2 
// task #1, #2, #3
public class Car {

    public String motor;
    public Integer maximumSpeed;
    public Integer passengers;
    public String color;
    public Boolean motorIsOn = true;
    public date currentDate = Date.today(); 
    //public Radio carRadio;
}

/* 
Car car1 = new Car();
car1.motor = 'V6';
car1.maximumSpeed = 80;
car1.passengers = 5;
car1.color =  'Red';
System.debug (car1);


Car car2 = new Car();
car2.motor = 'XTT-997';
car2.maximumSpeed = 210;
car2.passengers = 2;
car2.color =  'White';
System.debug (car2);

Car car3 = new Car();
car3.motor = 'DS';
car3.maximumSpeed = 190;
car3.passengers = 5;
car3.color =  'Grey';
System.debug (car3);

Questions: 
1. would it work without car1 car2?
2. why we use car1 and car2 and how to call it, prefix? alias?
3. what controles order of the variables in output and does it matter in any use cases?

*/