// Homework #2
// Tasks #8
public class Company {
    public String name;
 	public Employee CEO;
    public Department salesDepartment;
	public Department developmentDepartment;
	public Department humanResourcesDepartment;
}

/*
Employee emp1 = new Employee();
emp1.firstName = 'Johny';
emp1.lastName = 'Mnemonic';
emp1.salary = 120000;
emp1.yearsOfService = 10;
System.debug (emp1);

Employee emp2 = new Employee();
emp2.firstName = 'Stan';
emp2.lastName = 'Smith';
emp2.salary = 100000;
emp2.yearsOfService = 5;
System.debug (emp2);

Employee emp3 = new Employee();
emp3.firstName = 'Caro';
emp3.lastName = 'Black';
emp3.salary = 112000;
emp3.yearsOfService = 7;
System.debug (emp3);

Department dep1 = new Department();
dep1.name = 'Sales';
dep1.budget = 1000000;     
dep1.manager = emp1;
dep1.supervisor = emp2;
dep1.contactPerson = emp3;
System.debug (dep1);

Department dep2 = new Department();
dep2.name = 'Marketing';
dep2.budget = 1000000;     
dep2.manager = emp1;
dep2.supervisor = emp2;
dep2.contactPerson = emp3;
System.debug (dep2);

Department dep3 = new Department();
dep3.name = 'HR';
dep3.budget = 1000000;     
dep3.manager = emp1;
dep3.supervisor = emp2;
dep3.contactPerson = emp3;
System.debug (dep3);

Company com1 = new Company();
com1.name = 'Salesforce';
com1.CEO = emp1;
com1.salesDepartment = dep1;
com1.developmentDepartment = dep2;
com1.humanResourcesDepartment = dep3;
System.debug (com1);

Company com2 = new Company();
com2.name = 'Oracle';
com2.CEO = emp2;
com2.salesDepartment = dep1;
com2.developmentDepartment = dep2;
com2.humanResourcesDepartment = dep3;
System.debug (com2);

Company com3 = new Company();
com3.name = 'Amazon';
com3.CEO = emp3;
com3.salesDepartment = dep1;
com3.developmentDepartment = dep2;
com3.humanResourcesDepartment = dep3;
System.debug (com3);
*/