// Homework #2
// Tasks #7
public class Department {
	public String name;
    public Integer budget;
    public Employee manager;
    public Employee supervisor;
    public Employee contactPerson;
    
}
/*
Employee emp1 = new Employee();
emp1.firstName = 'Johny';
emp1.lastName = 'Mnemonic';
emp1.salary = 120000;
emp1.yearsOfService = 10;
System.debug (emp1);

Employee emp2 = new Employee();
emp2.firstName = 'Stan';
emp2.lastName = 'Smith';
emp2.salary = 100000;
emp2.yearsOfService = 5;
System.debug (emp2);

Employee emp3 = new Employee();
emp3.firstName = 'Caro';
emp3.lastName = 'Black';
emp3.salary = 112000;
emp3.yearsOfService = 7;
System.debug (emp3);

Department dep1 = new Department();
dep1.name = 'Sales';
dep1.budget = 1000000;     
dep1.manager = emp1;
dep1.supervisor = emp2;
dep1.contactPerson = emp3;
System.debug (dep1);
*/